Revert removal of minor versions of dependencies.
stackabletech/agent-integration-tests pull request #28
Opened 2021-05-27 11:55 UTC by razvan

2021-05-27 15:19 UTC, siegfriedweber commented
`indoc` was set to version `1.0`.

2021-05-27 15:20 UTC, siegfriedweber requested changes
`indoc` was set to version `1.0`.

2021-05-28 07:27 UTC, lfrancke approved these changes

2021-05-28 08:46 UTC, siegfriedweber approved these changes
LGTM

2021-05-28 09:07 UTC, merged